// pages/account/personal-reward/personal-reward.js
const api=require("../../../utils/api.js")
Page({
  data: {
    allFlag:"act",
    invationFlag:"",
    recommendFlag:"",
    putFlag:"",
    moneyDetail:{},
    userFlowingWater:{},
    pageNum:1
  },
  onLoad: function (options) {
    var _this=this;
    wx.request({
      url:api.getUserMsg,
      method:"GET",
      header:{
        sessionId: wx.getStorageSync('sessionId')
      },
      data:{

      },
      success(res){
        console.log(res)
        if(res.data.msg=="success"){
          _this.setData({
            moneyDetail:res.data.data
          })
        }
      },
      fail(error){
        console.log(error)
      }
    })
    this.requestData(-1,this.data.pageNum,10);
  },
  requestData(type,page,pageSize){
    var _this=this;
    wx.request({
      url:api.userFlowingWater,
      method:"GET",
      header:{
        sessionId: wx.getStorageSync('sessionId')
      },
      data:{
        type:type,
        page:page,
        pageSize:pageSize
      },
      success(res){
        console.log(res)
        if(res.data.msg=="success"){
          _this.setData({
            userFlowingWater:res.data.data
          })
        }
        console.log(_this.data.userFlowingWater,"a")
      },
      fail(error){
        console.log(error)
      }
    })
  },
  all(){
    this.setData({
      allFlag:"act",
      invationFlag:"",
      recommendFlag:"",
      putFlag:"",
    })
    this.requestData(-1,this.data.pageNum,10);
  },
  invation(){
    this.setData({
      allFlag:"",
      invationFlag:"act",
      recommendFlag:"",
      putFlag:"",
    })
    this.requestData(-1,this.data.pageNum,10);
  },
  recommend(){
    this.setData({
      allFlag:"",
      invationFlag:"",
      recommendFlag:"act",
      putFlag:"",
    })
  },
  put(){
    this.setData({
      allFlag:"",
      invationFlag:"",
      recommendFlag:"",
      putFlag:"act",
    })
  }
})